
package com.stockearte_backend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatalogoService", targetNamespace = "http://stockearte-backend.com/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/Distribuidos/Java/src/main/resources/CatalogoSoapService.wsdl")
public class CatalogoService
    extends Service
{

    private final static URL CATALOGOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATALOGOSERVICE_EXCEPTION;
    private final static QName CATALOGOSERVICE_QNAME = new QName("http://stockearte-backend.com/", "CatalogoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/Distribuidos/Java/src/main/resources/CatalogoSoapService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGOSERVICE_WSDL_LOCATION = url;
        CATALOGOSERVICE_EXCEPTION = e;
    }

    public CatalogoService() {
        super(__getWsdlLocation(), CATALOGOSERVICE_QNAME);
    }

    public CatalogoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGOSERVICE_QNAME, features);
    }

    public CatalogoService(URL wsdlLocation) {
        super(wsdlLocation, CATALOGOSERVICE_QNAME);
    }

    public CatalogoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGOSERVICE_QNAME, features);
    }

    public CatalogoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatalogoServicePortType
     */
    @WebEndpoint(name = "CatalogoServicePort")
    public CatalogoServicePortType getCatalogoServicePort() {
        return super.getPort(new QName("http://stockearte-backend.com/", "CatalogoServicePort"), CatalogoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns CatalogoServicePortType
     */
    @WebEndpoint(name = "CatalogoServicePort")
    public CatalogoServicePortType getCatalogoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stockearte-backend.com/", "CatalogoServicePort"), CatalogoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGOSERVICE_EXCEPTION!= null) {
            throw CATALOGOSERVICE_EXCEPTION;
        }
        return CATALOGOSERVICE_WSDL_LOCATION;
    }

}
