
package com.stockearte_backend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatalogoServicePortType", targetNamespace = "http://stockearte-backend.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatalogoServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.CreateCatalogoResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/createCatalogo")
    @WebResult(name = "createCatalogoResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public CreateCatalogoResponse createCatalogo(
        @WebParam(name = "createCatalogoRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        CreateCatalogoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.UpdateCatalogoResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/updateCatalogo")
    @WebResult(name = "updateCatalogoResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public UpdateCatalogoResponse updateCatalogo(
        @WebParam(name = "updateCatalogoRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        UpdateCatalogoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.DeleteCatalogoResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/deleteCatalogo")
    @WebResult(name = "deleteCatalogoResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public DeleteCatalogoResponse deleteCatalogo(
        @WebParam(name = "deleteCatalogoRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        DeleteCatalogoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.GetAllCatalogoResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/getAllCatalogo")
    @WebResult(name = "getAllCatalogoResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public GetAllCatalogoResponse getAllCatalogo(
        @WebParam(name = "getAllCatalogoRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        GetAllCatalogoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.GetCatalogoByIdResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/getCatalogoById")
    @WebResult(name = "getCatalogoByIdResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public GetCatalogoByIdResponse getCatalogoById(
        @WebParam(name = "getCatalogoByIdRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        GetCatalogoByIdRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.ExportarCatalogoPDFResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/exportarCatalogoPDF")
    @WebResult(name = "exportarCatalogoPDFResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public ExportarCatalogoPDFResponse exportarCatalogoPDF(
        @WebParam(name = "exportarCatalogoPDFRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        ExportarCatalogoPDFRequest parameters);

}
