
package com.stockearte_backend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FiltersService", targetNamespace = "http://stockearte-backend.com/", wsdlLocation = "file:/C:/Users/Nahu/Documents/stockearte-backend-2/src/main/resources/FiltersSoapService.wsdl")
public class FiltersService
    extends Service
{

    private final static URL FILTERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILTERSSERVICE_EXCEPTION;
    private final static QName FILTERSSERVICE_QNAME = new QName("http://stockearte-backend.com/", "FiltersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Nahu/Documents/stockearte-backend-2/src/main/resources/FiltersSoapService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILTERSSERVICE_WSDL_LOCATION = url;
        FILTERSSERVICE_EXCEPTION = e;
    }

    public FiltersService() {
        super(__getWsdlLocation(), FILTERSSERVICE_QNAME);
    }

    public FiltersService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILTERSSERVICE_QNAME, features);
    }

    public FiltersService(URL wsdlLocation) {
        super(wsdlLocation, FILTERSSERVICE_QNAME);
    }

    public FiltersService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILTERSSERVICE_QNAME, features);
    }

    public FiltersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FiltersService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FiltersServicePortType
     */
    @WebEndpoint(name = "FiltersServicePort")
    public FiltersServicePortType getFiltersServicePort() {
        return super.getPort(new QName("http://stockearte-backend.com/", "FiltersServicePort"), FiltersServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FiltersServicePortType
     */
    @WebEndpoint(name = "FiltersServicePort")
    public FiltersServicePortType getFiltersServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stockearte-backend.com/", "FiltersServicePort"), FiltersServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILTERSSERVICE_EXCEPTION!= null) {
            throw FILTERSSERVICE_EXCEPTION;
        }
        return FILTERSSERVICE_WSDL_LOCATION;
    }

}
