
package com.stockearte_backend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FiltersServicePortType", targetNamespace = "http://stockearte-backend.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FiltersServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.CreateFiltersModelResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/createFiltersModel")
    @WebResult(name = "createFiltersModelResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public CreateFiltersModelResponse createFiltersModel(
        @WebParam(name = "createFiltersModelRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        CreateFiltersModelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.UpdateFiltersModelResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/updateFiltersModel")
    @WebResult(name = "updateFiltersModelResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public UpdateFiltersModelResponse updateFiltersModel(
        @WebParam(name = "updateFiltersModelRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        UpdateFiltersModelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.stockearte_backend.DeleteFiltersModelResponse
     */
    @WebMethod(action = "http://stockearte-backend.com/deleteFiltersModel")
    @WebResult(name = "deleteFiltersModelResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public DeleteFiltersModelResponse deleteFiltersModel(
        @WebParam(name = "deleteFiltersModelRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        DeleteFiltersModelRequest parameters);

}
