
package com.unla.stockearte.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * SOAP Service for managing Purchase Orders.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrderService", targetNamespace = "http://stockearte-backend.com/", wsdlLocation = "file:/C:/Users/rricciardulli/Desktop/Personal/UNLa/4to/Distribuidos/stockearte-backend/src/main/resources/PurchaseOrderService.wsdl")
public class PurchaseOrderService
    extends Service
{

    private final static URL PURCHASEORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERSERVICE_EXCEPTION;
    private final static QName PURCHASEORDERSERVICE_QNAME = new QName("http://stockearte-backend.com/", "PurchaseOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/rricciardulli/Desktop/Personal/UNLa/4to/Distribuidos/stockearte-backend/src/main/resources/PurchaseOrderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERSERVICE_WSDL_LOCATION = url;
        PURCHASEORDERSERVICE_EXCEPTION = e;
    }

    public PurchaseOrderService() {
        super(__getWsdlLocation(), PURCHASEORDERSERVICE_QNAME);
    }

    public PurchaseOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERSERVICE_QNAME, features);
    }

    public PurchaseOrderService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERSERVICE_QNAME);
    }

    public PurchaseOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERSERVICE_QNAME, features);
    }

    public PurchaseOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderPortType
     */
    @WebEndpoint(name = "PurchaseOrderPort")
    public PurchaseOrderPortType getPurchaseOrderPort() {
        return super.getPort(new QName("http://stockearte-backend.com/", "PurchaseOrderPort"), PurchaseOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderPortType
     */
    @WebEndpoint(name = "PurchaseOrderPort")
    public PurchaseOrderPortType getPurchaseOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stockearte-backend.com/", "PurchaseOrderPort"), PurchaseOrderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERSERVICE_EXCEPTION!= null) {
            throw PURCHASEORDERSERVICE_EXCEPTION;
        }
        return PURCHASEORDERSERVICE_WSDL_LOCATION;
    }

}
