
package com.unla.stockearte.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrderPortType", targetNamespace = "http://stockearte-backend.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurchaseOrderPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns src.main.java.com.unla.stockearte.soap.GetPurchaseOrdersResponse
     */
    @WebMethod(operationName = "GetPurchaseOrders", action = "http://stockearte-backend.com/GetPurchaseOrders")
    @WebResult(name = "GetPurchaseOrdersResponse", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
    public GetPurchaseOrdersResponse getPurchaseOrders(
        @WebParam(name = "GetPurchaseOrdersRequest", targetNamespace = "http://stockearte-backend.com/", partName = "parameters")
        GetPurchaseOrdersRequest parameters);

}
