/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package stockearte.unla.edu.ar.api;

import stockearte.unla.edu.ar.model.GetStoresResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "stores", description = "the stores API")
public interface StoresApi {

    @ApiOperation(value = "Get a list of stores", nickname = "storesGet", notes = "", response = GetStoresResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of stores", response = GetStoresResponse.class) })
    @RequestMapping(value = "/stores",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GetStoresResponse> storesGet(@ApiParam(value = "Filter stores by code") @Valid @RequestParam(value = "code", required = false) String code
,@ApiParam(value = "Filter stores by enabled status") @Valid @RequestParam(value = "enabled", required = false) String enabled
);

}
