/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package stockearte.unla.edu.ar.api;

import stockearte.unla.edu.ar.model.GetUsersResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "users", description = "the users API")
public interface UsersApi {

    @ApiOperation(value = "Get a list of users", nickname = "usersGet", notes = "", response = GetUsersResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of users", response = GetUsersResponse.class) })
    @RequestMapping(value = "/users",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GetUsersResponse> usersGet(@ApiParam(value = "Filter users by username") @Valid @RequestParam(value = "username", required = false) String username
,@ApiParam(value = "Filter users by store code") @Valid @RequestParam(value = "storeCode", required = false) String storeCode
);

}
